<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" >

    <xacro:include filename="inertial_macros.xacro"/>

    <!-- Chassis properties -->
    <xacro:property name="chassis_length" value="0.70"/>
    <xacro:property name="chassis_width" value="0.50"/>
    <xacro:property name="chassis_height" value="0.10"/>
    <xacro:property name="chassis_mass" value="1.0"/>

    <!-- Storage properties -->
    <xacro:property name="storage_length" value="0.43"/>
    <xacro:property name="storage_width" value="0.43"/>
    <xacro:property name="storage_height" value="0.47"/>
    <xacro:property name="storage_mass" value="1.0"/>

    <!-- Wheel properties -->
    <xacro:property name="wheel_radius" value="0.1"/>
    <xacro:property name="wheel_thickness" value="0.026"/>
    <xacro:property name="wheel_mass" value="0.05"/>
    <xacro:property name="wheel_offset_x" value="${chassis_length/3}"/>
    <xacro:property name="wheel_offset_y" value="${chassis_width/2+0.013}"/>
    <xacro:property name="wheel_offset_z" value="0"/>


    <material name="white">
        <color rgba="1 1 1 1" />
    </material>

    <material name="orange">
        <color rgba="1 0.3 0.1 1"/>
    </material>

    <material name="blue">
        <color rgba="0.2 0.2 1 1"/>
    </material>

    <material name="black">
        <color rgba="0 0 0 1"/>
    </material>

    <material name="red">
        <color rgba="1 0 0 1"/>
    </material>

    <!-- BASE LINK -->

    <link name="base_link">

    </link>

    <!-- BASE_FOOTPRINT LINK -->

    <joint name="base_footprint_joint" type="fixed">
        <parent link="base_link"/>
        <child link="base_footprint"/>
        <origin xyz="0 0 0" rpy="0 0 0"/>
    </joint>

    <link name="base_footprint">
    </link>


    <!-- CHASSIS LINK -->

    <joint name="chassis_joint" type="fixed">
        <parent link="base_link"/>
        <child link="chassis"/>
        <origin xyz="${-chassis_length/2} 0 ${-wheel_radius/2}"/>
    </joint>

    <link name="chassis">
        <visual>
            <origin xyz="${chassis_length/2} 0 ${chassis_height/2}"/>
            <geometry>
                <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
            </geometry>
            <material name="orange"/>
        </visual>
        <collision>
            <origin xyz="${chassis_length/2} 0 ${chassis_height/2}"/>
            <geometry>
                <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
            </geometry>
        </collision>
        <xacro:inertial_box mass="0.5" x="${chassis_length}" y="${chassis_width}" z="${chassis_height}">
            <origin xyz="${chassis_length/2} 0 ${chassis_height/2}" rpy="0 0 0"/>
        </xacro:inertial_box>
    </link>

    <gazebo reference="chassis">
        <material>Gazebo/Orange</material>
    </gazebo>

    <!-- STORAGE BOX LINK -->
    <joint name="storage_box_joint" type="fixed">
        <parent link="chassis"/>
        <child link="storage_box"/>
        <origin xyz="0 0 0"/>
    </joint>

    <link name="storage_box">
        <visual>
            <origin xyz="${storage_length/2} 0 ${storage_height/2+chassis_height}"/>
            <geometry>
                <box size="${storage_length} ${storage_width} ${storage_height}"/>
            </geometry>
            <material name="blue"/>
        </visual>
        <collision>
            <origin xyz="${storage_length/2} 0 ${storage_height/2}"/>
            <geometry>
                <box size="${storage_length} ${storage_width} ${storage_height}"/>
            </geometry>
        </collision>
        <xacro:inertial_box mass="0.5" x="${storage_length}" y="${storage_width}" z="${storage_height}">
            <origin xyz="${storage_length/2} 0 ${storage_height/2}" rpy="0 0 0"/>
        </xacro:inertial_box>
    </link>

    <gazebo reference="storage_box">
        <material>Gazebo/Blue</material>
    </gazebo>

    <!-- LEFT REAR WHEEL LINK -->

    <joint name="left_rear_wheel_joint" type="continuous">
        <parent link="base_link"/>
        <child link="left_rear_wheel"/>
        <origin xyz="${-wheel_offset_x} ${wheel_offset_y} 0" rpy="-${pi/2} 0 0" />
        <axis xyz="0 0 1"/>
    </joint>

    <link name="left_rear_wheel">
        <visual>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_thickness}"/>
            </geometry>
            <material name="blue"/>
        </visual>
        <collision>
            <geometry>
                <sphere radius="${wheel_radius}"/>
            </geometry>
        </collision>
        <xacro:inertial_cylinder mass="${wheel_mass}" length="${wheel_thickness}" radius="${wheel_radius}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </link>

    <gazebo reference="left_rear_wheel">
        <material>Gazebo/Blue</material>
    </gazebo>

    <!-- LEFT FRONT WHEEL LINK -->
    <!-- make type="continuous" for real diff drive -->

    <joint name="left_front_wheel_joint" type="fixed">
        <parent link="base_link"/>
        <child link="left_front_wheel"/>
        <origin xyz="${wheel_offset_x} ${wheel_offset_y} 0" rpy="-${pi/2} 0 0" />
        <axis xyz="0 0 1"/>
    </joint>

    <link name="left_front_wheel">
        <visual>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_thickness}"/>
            </geometry>
            <material name="blue"/>
        </visual>
        <collision>
            <geometry>
                <sphere radius="${wheel_radius}"/>
            </geometry>
        </collision>
        <xacro:inertial_cylinder mass="${wheel_mass}" length="${wheel_thickness}" radius="${wheel_radius}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </link>

    <gazebo reference="left_front_wheel">
        <material>Gazebo/Blue</material>
        <mu1 value="0.001"/>
        <mu2 value="0.001"/>
    </gazebo>


    <!-- RIGHT REAR WHEEL LINK -->

    <joint name="right_rear_wheel_joint" type="continuous">
        <parent link="base_link"/>
        <child link="right_rear_wheel"/>
        <origin xyz="${-wheel_offset_x} ${-wheel_offset_y} 0" rpy="${pi/2} 0 0" />
        <axis xyz="0 0 -1"/>
    </joint>

    <link name="right_rear_wheel">
        <visual>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_thickness}"/>
            </geometry>
            <material name="blue"/>
        </visual>
        <collision>
            <geometry>
                <sphere radius="${wheel_radius}"/>
            </geometry>
        </collision>
        <xacro:inertial_cylinder mass="${wheel_mass}" length="${wheel_thickness}" radius="${wheel_radius}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </link>

    <gazebo reference="right_rear_wheel">
        <material>Gazebo/Blue</material>
    </gazebo>

    <!-- RIGHT FRONT WHEEL LINK -->
    <!-- make type="continuous" for real diff drive -->
    <joint name="right_front_wheel_joint" type="fixed">  
        <parent link="base_link"/>
        <child link="right_front_wheel"/>
        <origin xyz="${wheel_offset_x} ${-wheel_offset_y} 0" rpy="${pi/2} 0 0" />
        <axis xyz="0 0 -1"/>
    </joint>

    <link name="right_front_wheel">
        <visual>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_thickness}"/>
            </geometry>
            <material name="blue"/>
        </visual>
        <collision>
            <geometry>
                <sphere radius="${wheel_radius}"/>
            </geometry>
        </collision>
        <xacro:inertial_cylinder mass="${wheel_mass}" length="${wheel_thickness}" radius="${wheel_radius}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </link>

    <gazebo reference="right_front_wheel">
        <material>Gazebo/Blue</material>
        <mu1 value="0.001"/>
        <mu2 value="0.001"/>
    </gazebo>    
</robot>